# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and deploy project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build
    - name: Publish
      run: gradle -PSONATYPE_USER=${{ secrets.SONATYPE_USER }} -PSONATYPE_PASSWORD=${{ secrets.SONATYPE_PASSWORD }}  -PPGP_SIGNED_KEY="${{ secrets.PGP_SIGNED_KEY }}" -PPGP_SIGNED_PASSWORD="${{ secrets.PGP_SIGNED_PASSWORD }}" publish
